### ISSUE TITLE
Forwarding the `rustls` provider settings

### ISSUE THREAD

**Issue by LecrisUT** [rustls/hyper-rustls#288]
It would be good to use a design of the features similar to [`axum-server`](https://github.com/programatik29/axum-server/blob/76bb0318c1776cbcb4f55a474367ed10f2efb188/Cargo.toml#L17-L18), i.e.:
```toml
tls-rustls = ["tls-rustls-no-provider", "rustls/aws-lc-rs"]
tls-rustls-no-provider = [...]
```
This would make it easier to forward these options down the chain of dependencies.
